# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cv_subsection',
            new_name='CVSubsection',
        ),
        migrations.DeleteModel(
            name='Cv_Section',
        ),
        migrations.AlterField(
            model_name='cvsubsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='cv.CVSection'),
        ),
    ]
