# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200821_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsection',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
